#!/usr/bin/env python3
"""Build the dashboard gallery: docs/dashboards/index.html (browse folder) + docs/gallery.html (full index).

The interactive HTML dashboards are the BASE product; plot4gmns/MOE static figures are ADDITIONAL.
Corridor state-views (calendar / network / space-time) follow the NeXTA-AI-Gen sample naming
(<view>_<corridor>_<date>.html). Run after regenerating dashboards/figures.
Usage: python build_gallery.py
"""
import os, sys, glob

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
DOCS = os.path.join(ROOT, "docs")

# Additional static-figure sections (plot4gmns first, then MOE) — the dashboards are the base, above these.
SECTIONS = [
    ("Additional: plot4gmns static figures", "p4g_native_gallery",
     "Supplementary static images — the plot4gmns catalog reimplemented natively (no pandas/Shapely/"
     "keplergl): network nodes/links/zones/POI, by-attribute, distributions, demand matrix + OD, lanes, movements."),
    ("Additional: MOE & analytics figures (report-ready)", "moe_gallery",
     "Traffic-Speed bandwidth, space-time speed/density contours, corridor profiles, PeMS/RITIS bottleneck "
     "ranking, global city-store coverage. Intuitive green(fast)->red(slow)."),
]

# Pretty names for the shipped base dashboards.
PRETTY = {
    "01_sioux_falls": "Sioux Falls (classic test network)",
    "02_chicago_sketch": "Chicago Sketch (regional demand)",
    "05_toy_bottleneck": "Toy — bottleneck", "05_toy_merge": "Toy — merge", "05_toy_signal": "Toy — signal",
    "07_west_jordan": "West Jordan, UT (real corridor)",
}
CORRIDOR_TOKENS = ("calendar", "spacetime", "_network_")

# The AI value proposition — shown on the gallery so users know these are generatable on request.
AI_NOTE = ("<b>Generated by AI — ask for more.</b> Every page here was produced by the assistant from a "
           "GMNS network plus a link speed / <code>link_performance</code> table (or an AI solver's output). "
           "Ask it to generate the same views for <b>additional data</b> — e.g. the <b>ITS I-95 corridors</b>, "
           "or <b>other years</b> of the same corridor. Provide the network + speeds and name the corridor and date; "
           "the calendar view already spans a whole year, so multi-year is just another run.")

def imgs(folder):
    return sorted(os.path.basename(p) for p in glob.glob(os.path.join(DOCS, folder, "*.png")))

def dashboards():
    return sorted(os.path.basename(p) for p in glob.glob(os.path.join(DOCS, "dashboards", "*.html"))
                  if os.path.basename(p) != "index.html")

def classify(names):
    base, corridor = [], []
    for n in names:
        (corridor if any(t in n for t in CORRIDOR_TOKENS) else base).append(n)
    return base, corridor

def corridor_groups(names):
    groups = {}
    for n in names:
        cid = n.split("_")[0]                                   # e.g. "I210E"
        view = ("calendar" if "calendar" in n else "space-time" if "spacetime" in n
                else "network" if "network" in n else "view")
        groups.setdefault(cid, {})[view] = n
    return groups

def datasets():
    dd = os.path.join(ROOT, "datasets")
    return [n for n in (sorted(os.listdir(dd)) if os.path.isdir(dd) else [])
            if os.path.exists(os.path.join(dd, n, "link.csv"))]

CSS = """
 body{font:14px/1.5 system-ui,Segoe UI,Arial;margin:0;color:#222;background:#fafafa}
 header{background:#1d232b;color:#e6edf3;padding:18px 26px}
 header h1{margin:0;font-size:20px} header h1 span{color:#58a6ff}
 header p{margin:4px 0 0;color:#9aa7bd;font-size:13px}
 main{max-width:1200px;margin:0 auto;padding:20px 26px}
 section{margin:26px 0} h2{border-bottom:2px solid #eee;padding-bottom:6px}
 .tag{font-size:11px;font-weight:600;color:#fff;background:#2563eb;border-radius:10px;padding:2px 9px;vertical-align:middle}
 .tag.alt{background:#8a8f98}
 .desc{color:#555;margin:-4px 0 12px}
 .ai{background:linear-gradient(135deg,#eef3ff,#e3ecff);border:1px solid #cdd9f5;border-left:4px solid #2563eb;
   border-radius:8px;padding:12px 16px;margin:14px 0;color:#26324a}
 .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:14px}
 figure{margin:0;background:#fff;border:1px solid #e5e5e5;border-radius:8px;overflow:hidden}
 figure img{width:100%;display:block;background:#fff}
 figure.db a{text-decoration:none}
 .dbthumb{height:132px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;
   font-size:42px;color:#2563eb;background:linear-gradient(135deg,#eef3ff,#dfe8ff);border-bottom:1px solid #d6e0f5}
 .dbthumb span{font-size:12px;color:#2563eb;font-weight:600}
 .dbthumb.cor{color:#b8562a;background:linear-gradient(135deg,#fff3ec,#ffe6d6);border-bottom:1px solid #f3d3bf}
 .dbthumb.cor span{color:#b8562a}
 figcaption{padding:6px 8px;font-size:11.5px;color:#444;border-top:1px solid #eee}
 .views a{display:inline-block;margin-right:10px;font-size:12.5px}
 .legend{font-size:12px;color:#666} .legend b{color:#333}
 ul{line-height:1.9} code{background:#eef;padding:1px 5px;border-radius:3px;font-size:12px}
"""

def db_card(n, cls=""):
    icon = "&#128506;" if not cls else "&#128197;" if "calendar" in n else "&#128512;"
    label = PRETTY.get(n[:-5], n[:-5].replace("_", " "))
    return (f'<figure class="db"><a href="{n}" target="_blank">'
            f'<div class="dbthumb {cls}">{icon}<span>open</span></div></a>'
            f'<figcaption>{label}</figcaption></figure>')


def write_folder_index(out):
    """docs/dashboards/index.html — the browsable gallery folder landing page (sample-style)."""
    base, corr = classify(dashboards())
    base_grid = "".join(db_card(n) for n in base)
    groups = corridor_groups(corr)
    cor_blocks = ""
    for cid, views in sorted(groups.items()):
        links = " ".join(f'<a href="{fn}" target="_blank">{v}</a>' for v, fn in
                          sorted(views.items(), key=lambda kv: {"calendar": 0, "network": 1, "space-time": 2}.get(kv[0], 9)))
        cor_blocks += (f'<figure class="db"><div class="dbthumb cor">&#128506;<span>{cid}</span></div>'
                       f'<figcaption><b>{cid}</b><div class="views">{links}</div></figcaption></figure>')
    cor_sec = (f'<section><h2>Corridor state-views <span class="tag">HTML</span></h2>'
               f'<p class="desc">Per corridor: <b>calendar</b> (whole year by day/year) &middot; <b>network</b> '
               f'(corridor map by mean speed) &middot; <b>space-time</b> (milepost&times;time speed heatmap). '
               f'Following the NeXTA-AI-Gen <code>&lt;view&gt;_&lt;corridor&gt;_&lt;date&gt;</code> convention.</p>'
               f'<div class="grid">{cor_blocks}</div></section>') if groups else ""
    html = f"""<!doctype html><html><head><meta charset="utf-8"><title>gui4gmns — dashboard gallery</title>
<style>{CSS}</style></head><body>
<header><h1><span>gui4gmns</span> dashboard gallery</h1>
<p>All dashboards in one folder — click any card to open. Self-contained, offline, no server.</p></header>
<main>
<div class="ai">{AI_NOTE}</div>
<section><h2>Network dashboards &mdash; the base <span class="tag">HTML</span></h2>
<p class="desc">Self-contained offline dashboards (network + basemap embedded): layers, MOE modes, trajectory
animation. gui4gmns's primary output. Large networks (ARC, Chicago Regional) are generate-on-demand.</p>
<div class="grid">{base_grid}</div></section>
{cor_sec}
<section class="legend"><b>Speed colors:</b> intuitive <b style="color:#2ca02c">green = free-flow</b> &rarr;
<b style="color:#d62728">red = jammed</b> (colorblind-safe palette available with <code>--cmap cb</code>).
&nbsp;·&nbsp; Full index incl. static figures: <a href="../gallery.html">gallery.html</a></section>
</main></body></html>"""
    open(out, "w", encoding="utf-8").write(html)
    return len(base), len(groups)


def write_gallery(out):
    """docs/gallery.html — the full index: dashboards (base) + additional static figures + docs."""
    base, corr = classify(dashboards())
    db_grid = "".join(
        f'<figure class="db"><a href="dashboards/{n}" target="_blank"><div class="dbthumb">&#128506;<span>open</span></div></a>'
        f'<figcaption>{PRETTY.get(n[:-5], n[:-5].replace("_"," "))}</figcaption></figure>' for n in base)
    cor_note = (f' &middot; plus <b>{len(corridor_groups(corr))}</b> corridor state-view set(s) '
                f'(calendar/network/space-time)') if corr else ""
    base_sec = (f'<section><h2>Interactive dashboards &mdash; the base <span class="tag">HTML</span></h2>'
                f'<p class="desc">All dashboards live in one browsable folder: '
                f'<a href="dashboards/index.html"><b>docs/dashboards/</b></a>{cor_note}. Self-contained &amp; '
                f'offline; rebuild with <code>python renderers/build_dashboards.py</code>.</p>'
                f'<div class="ai">{AI_NOTE}</div><div class="grid">{db_grid}</div></section>')
    cards = ""
    for title, folder, desc in SECTIONS:
        names = imgs(folder)
        if not names: continue
        thumbs = "".join(
            f'<figure><a href="{folder}/{n}" target="_blank"><img src="{folder}/{n}" loading="lazy"></a>'
            f'<figcaption>{n.replace(".png","").replace("_"," ")}</figcaption></figure>' for n in names)
        cards += f'<section><h2>{title} <span class="tag alt">static</span></h2><p class="desc">{desc}</p><div class="grid">{thumbs}</div></section>'
    ds = datasets()
    ds_rows = "".join(f'<li><b>{n}</b> — <code>python ai-gen/gui4gmns.py datasets/{n}</code> '
                      f'-&gt; <code>datasets/{n}/dashboard.html</code> + <code>figures/</code></li>' for n in ds)
    html = f"""<!doctype html><html><head><meta charset="utf-8"><title>gui4gmns gallery</title>
<style>{CSS}</style></head><body>
<header><h1><span>gui4gmns</span> gallery</h1>
<p>HTML dashboards are the base (interactive, one folder); plot4gmns &amp; MOE figures are additional static images.</p></header>
<main>{base_sec}{cards}
<section><h2>Generate for any dataset ({len(ds)} demos)</h2>
<p class="desc">Every dataset produces a self-contained dashboard (base) + a static figure set (additional):</p>
<ul>{ds_rows}</ul></section>
<section><h2>Docs</h2><ul>
<li><a href="PACKAGE.md">PACKAGE.md</a> — package overview &amp; review checklist</li>
<li><a href="DATASETS_COVERAGE.md">DATASETS_COVERAGE.md</a> — flagship + partial-coverage matrix</li>
<li><a href="FINAL_REVIEW.md">FINAL_REVIEW.md</a> · <a href="TRB_VIZ_REVIEW.md">TRB viz</a> · <a href="STAKEHOLDER_REVIEW.md">stakeholder</a> · <a href="ROADMAP.md">roadmap</a></li>
</ul></section></main></body></html>"""
    open(out, "w", encoding="utf-8").write(html)
    return len(base)

def main():
    idx = os.path.join(DOCS, "dashboards", "index.html")
    nb, ng = write_folder_index(idx)
    ndb = write_gallery(os.path.join(DOCS, "gallery.html"))
    nfig = sum(len(imgs(f)) for _, f, _ in SECTIONS)
    print(f"wrote docs/dashboards/index.html ({nb} network dashboards, {ng} corridor set(s))")
    print(f"wrote docs/gallery.html ({ndb} dashboards, {nfig} figures, {len(datasets())} datasets)")

if __name__ == "__main__":
    main()
