#!/usr/bin/env python3
"""Build the dashboard gallery: docs/dashboards/index.html (browse folder) + docs/gallery.html (full index).

Interactive HTML dashboards are the BASE product; plot4gmns/MOE static figures are ADDITIONAL. Each base
dashboard card carries a real network thumbnail (network_thumb) + stats + description, following the
gui4gmns sample (rich per-network info, not a generic icon). Corridor state-views (calendar / network /
space-time) follow the <view>_<corridor>_<date>.html convention.
Usage: python build_gallery.py
"""
import os, sys, glob, importlib.util

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
DOCS = os.path.join(ROOT, "docs")

_spec = importlib.util.spec_from_file_location("network_thumb", os.path.join(HERE, "network_thumb.py"))
network_thumb = importlib.util.module_from_spec(_spec); _spec.loader.exec_module(network_thumb)

SECTIONS = [
    ("Additional: plot4gmns static figures", "p4g_native_gallery",
     "Supplementary static images — the plot4gmns catalog reimplemented natively (no pandas/Shapely/"
     "keplergl): network nodes/links/zones/POI, by-attribute, distributions, demand matrix + OD, lanes, movements."),
    ("Additional: MOE & analytics figures (report-ready)", "moe_gallery",
     "Traffic-Speed bandwidth, space-time speed/density contours, corridor profiles, PeMS/RITIS bottleneck "
     "ranking, global city-store coverage. Intuitive green(fast)->red(slow)."),
]

# base dashboard -> (title, one-line description). Toys are excluded (abstract stubs, not gallery-readable).
PRETTY = {
    "01_sioux_falls": ("Sioux Falls", "Classic transportation test network — the standard TAP benchmark."),
    "02_chicago_sketch": ("Chicago Sketch", "Regional sketch network with demand, assignment and link performance."),
    "07_west_jordan": ("West Jordan, UT", "Real signalized corridor; links colored by observed mean speed."),
}
CORRIDOR_TOKENS = ("calendar", "spacetime", "_network_")

AI_NOTE = ("<b>Generated by AI — ask for more.</b> Every page here was produced by the assistant from a "
           "GMNS network plus a link speed / <code>link_performance</code> table (or an AI solver's output). "
           "Ask it to generate the same views for <b>additional data</b> — e.g. the <b>ITS I-95 corridors</b>, "
           "or <b>other years</b> of the same corridor. Provide the network + speeds and name the corridor and date; "
           "the calendar view already spans a whole year, so multi-year is just another run.")

def imgs(folder):
    return sorted(os.path.basename(p) for p in glob.glob(os.path.join(DOCS, folder, "*.png")))

def dashboards():
    return sorted(os.path.basename(p) for p in glob.glob(os.path.join(DOCS, "dashboards", "*.html"))
                  if os.path.basename(p) != "index.html")

def classify(names):
    base, corr = [], []
    for n in names:
        (corr if any(t in n for t in CORRIDOR_TOKENS) else base).append(n)
    return base, corr

def corridor_groups(names):
    groups = {}
    for n in names:
        cid = n.split("_")[0]
        view = ("calendar" if "calendar" in n else "space-time" if "spacetime" in n
                else "network" if "network" in n else "view")
        groups.setdefault(cid, {})[view] = n
    return groups

def datasets():
    dd = os.path.join(ROOT, "datasets")
    return [n for n in (sorted(os.listdir(dd)) if os.path.isdir(dd) else [])
            if os.path.exists(os.path.join(dd, n, "link.csv")) and "toy" not in n.lower()]

def build_thumbs(base_names):
    """Render a real network thumbnail per base dashboard; return {name: stats}."""
    out = {}
    for n in base_names:
        ds = n[:-5]                                             # strip .html -> dataset folder
        folder = os.path.join(ROOT, "datasets", ds)
        if not os.path.exists(os.path.join(folder, "node.csv")):
            out[n] = None; continue
        try:
            out[n] = network_thumb.render(folder, os.path.join(DOCS, "dashboards", "thumbs", ds + ".svg"))
        except Exception as e:
            print(f"  (thumb skipped {ds}: {type(e).__name__})"); out[n] = None
    return out

CSS = """
 body{font:14px/1.5 system-ui,Segoe UI,Arial;margin:0;color:#222;background:#fafafa}
 header{background:#1d232b;color:#e6edf3;padding:18px 26px}
 header h1{margin:0;font-size:20px} header h1 span{color:#58a6ff}
 header p{margin:4px 0 0;color:#9aa7bd;font-size:13px}
 main{max-width:1200px;margin:0 auto;padding:20px 26px}
 section{margin:26px 0} h2{border-bottom:2px solid #eee;padding-bottom:6px}
 .tag{font-size:11px;font-weight:600;color:#fff;background:#2563eb;border-radius:10px;padding:2px 9px;vertical-align:middle}
 .tag.alt{background:#8a8f98}
 .desc{color:#555;margin:-4px 0 12px}
 .ai{background:linear-gradient(135deg,#eef3ff,#e3ecff);border:1px solid #cdd9f5;border-left:4px solid #2563eb;
   border-radius:8px;padding:12px 16px;margin:14px 0;color:#26324a}
 .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:14px}
 figure{margin:0;background:#fff;border:1px solid #e5e5e5;border-radius:8px;overflow:hidden;transition:box-shadow .15s}
 figure:hover{box-shadow:0 3px 12px rgba(0,0,0,.10)}
 figure img{width:100%;display:block;background:#f6f7f9}
 figure.db a{text-decoration:none}
 figcaption{padding:8px 10px;border-top:1px solid #eee}
 figcaption b{font-size:13px;color:#1d232b} figcaption .meta{font-size:11px;color:#2563eb;margin:2px 0}
 figcaption .d{font-size:11.5px;color:#555} figcaption.fig{font-size:11.5px;color:#444}
 .dbthumb{height:110px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;
   font-size:38px;color:#b8562a;background:linear-gradient(135deg,#fff3ec,#ffe6d6);border-bottom:1px solid #f3d3bf}
 .dbthumb span{font-size:12px;color:#b8562a;font-weight:600}
 .views a{display:inline-block;margin-right:10px;font-size:12.5px}
 .legend{font-size:12px;color:#666} .legend b{color:#333}
 ul{line-height:1.9} code{background:#eef;padding:1px 5px;border-radius:3px;font-size:12px}
"""

def rich_card(name, stats, prefix=""):
    """A base-dashboard card: real network thumbnail + title + stats + description."""
    ds = name[:-5]
    title, desc = PRETTY.get(ds, (ds.replace("_", " "), ""))
    if stats:
        meta = f'{stats["links"]:,} links &middot; {stats["nodes"]:,} nodes'
        if stats.get("zones"): meta += f' &middot; {stats["zones"]:,} zones'
        meta += f' &middot; by {stats["color_by"]}'
        thumb = f'<img src="{prefix}thumbs/{ds}.svg" loading="lazy" alt="{title} network">'
    else:
        meta, thumb = "", '<div class="dbthumb">&#128506;</div>'
    return (f'<figure class="db"><a href="{prefix}{name}" target="_blank">{thumb}</a>'
            f'<figcaption><b>{title}</b><div class="meta">{meta}</div><div class="d">{desc}</div></figcaption></figure>')

def corridor_section(corr, prefix=""):
    groups = corridor_groups(corr)
    if not groups: return ""
    blocks = ""
    for cid, views in sorted(groups.items()):
        order = {"calendar": 0, "network": 1, "space-time": 2}
        links = " ".join(f'<a href="{prefix}{fn}" target="_blank">{v}</a>'
                         for v, fn in sorted(views.items(), key=lambda kv: order.get(kv[0], 9)))
        blocks += (f'<figure class="db"><div class="dbthumb">&#128506;<span>{cid}</span></div>'
                   f'<figcaption><b>{cid} corridor</b><div class="views">{links}</div></figcaption></figure>')
    return (f'<section><h2>Corridor state-views <span class="tag">HTML</span></h2>'
            f'<p class="desc">Per corridor: <b>calendar</b> (whole year by day/year) &middot; <b>network</b> '
            f'(corridor map by mean speed) &middot; <b>space-time</b> (milepost&times;time speed heatmap). '
            f'gui4gmns <code>&lt;view&gt;_&lt;corridor&gt;_&lt;date&gt;</code> convention.</p>'
            f'<div class="grid">{blocks}</div>'
            f'<p class="legend" style="margin-top:8px">Corridor samples: <b>gui4gmns</b> / '
            f'<b>TrafficFlowBench-CA</b> benchmark; corridor speeds derived from <b>Caltrans PeMS</b> '
            f'(public agency data). Released for public use.</p></section>')

def write_folder_index(out, thumbs):
    base, corr = classify(dashboards())
    grid = "".join(rich_card(n, thumbs.get(n)) for n in base)
    html = f"""<!doctype html><html><head><meta charset="utf-8"><title>gui4gmns — dashboard gallery</title>
<style>{CSS}</style></head><body>
<header><h1><span>gui4gmns</span> dashboard gallery</h1>
<p>All dashboards in one folder — click any card to open. Self-contained, offline, no server.</p></header>
<main>
<div class="ai">{AI_NOTE}</div>
<section><h2>Network dashboards &mdash; the base <span class="tag">HTML</span></h2>
<p class="desc">Self-contained offline dashboards (network + basemap embedded): layers, MOE modes, trajectory
animation. gui4gmns's primary output. Large networks (ARC, Chicago Regional) are generate-on-demand.</p>
<div class="grid">{grid}</div></section>
{corridor_section(corr)}
<section class="legend"><b>Speed colors:</b> intuitive <b style="color:#2ca02c">green = free-flow</b> &rarr;
<b style="color:#d62728">red = jammed</b> (colorblind-safe palette available with <code>--cmap cb</code>).
&nbsp;·&nbsp; Full index incl. static figures: <a href="../gallery.html">gallery.html</a></section>
</main></body></html>"""
    open(out, "w", encoding="utf-8").write(html)
    return len(base), len(corridor_groups(corr))

def write_gallery(out, thumbs):
    base, corr = classify(dashboards())
    grid = "".join(rich_card(n, thumbs.get(n), prefix="dashboards/") for n in base)
    cor_note = (f' &middot; plus <b>{len(corridor_groups(corr))}</b> corridor state-view set(s)') if corr else ""
    base_sec = (f'<section><h2>Interactive dashboards &mdash; the base <span class="tag">HTML</span></h2>'
                f'<p class="desc">All dashboards live in one browsable folder: '
                f'<a href="dashboards/index.html"><b>docs/dashboards/</b></a>{cor_note}. Self-contained &amp; '
                f'offline; rebuild with <code>python renderers/build_dashboards.py</code>.</p>'
                f'<div class="ai">{AI_NOTE}</div><div class="grid">{grid}</div></section>')
    cards = ""
    for title, folder, desc in SECTIONS:
        names = imgs(folder)
        if not names: continue
        thumbs_h = "".join(
            f'<figure><a href="{folder}/{n}" target="_blank"><img src="{folder}/{n}" loading="lazy"></a>'
            f'<figcaption class="fig">{n.replace(".png","").replace("_"," ")}</figcaption></figure>' for n in names)
        cards += f'<section><h2>{title} <span class="tag alt">static</span></h2><p class="desc">{desc}</p><div class="grid">{thumbs_h}</div></section>'
    ds = datasets()
    ds_rows = "".join(f'<li><b>{n}</b> — <code>python ai-gen/gui4gmns.py datasets/{n}</code> '
                      f'-&gt; <code>datasets/{n}/dashboard.html</code> + <code>figures/</code></li>' for n in ds)
    html = f"""<!doctype html><html><head><meta charset="utf-8"><title>gui4gmns gallery</title>
<style>{CSS}</style></head><body>
<header><h1><span>gui4gmns</span> gallery</h1>
<p>HTML dashboards are the base (interactive, one folder); plot4gmns &amp; MOE figures are additional static images.</p></header>
<main>{base_sec}{cards}
<section><h2>Generate for any dataset ({len(ds)} demos)</h2>
<p class="desc">Every dataset produces a self-contained dashboard (base) + a static figure set (additional):</p>
<ul>{ds_rows}</ul></section>
<section><h2>Docs</h2><ul>
<li><a href="PACKAGE.md">PACKAGE.md</a> — package overview &amp; review checklist</li>
<li><a href="DATASETS_COVERAGE.md">DATASETS_COVERAGE.md</a> — flagship + partial-coverage matrix</li>
<li><a href="FINAL_REVIEW.md">FINAL_REVIEW.md</a> · <a href="TRB_VIZ_REVIEW.md">TRB viz</a> · <a href="STAKEHOLDER_REVIEW.md">stakeholder</a> · <a href="ROADMAP.md">roadmap</a></li>
</ul></section></main></body></html>"""
    open(out, "w", encoding="utf-8").write(html)
    return len(base)

def main():
    base, _ = classify(dashboards())
    thumbs = build_thumbs(base)
    nb, ng = write_folder_index(os.path.join(DOCS, "dashboards", "index.html"), thumbs)
    ndb = write_gallery(os.path.join(DOCS, "gallery.html"), thumbs)
    nfig = sum(len(imgs(f)) for _, f, _ in SECTIONS)
    print(f"wrote docs/dashboards/index.html ({nb} network dashboards + thumbnails, {ng} corridor set(s))")
    print(f"wrote docs/gallery.html ({ndb} dashboards, {nfig} figures, {len(datasets())} datasets)")

if __name__ == "__main__":
    main()
